# Generated by Django 3.2.4 on 2022-06-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Модерация'),
        ),
        migrations.AlterField(
            model_name='folders',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='Выберите Файл'),
        ),
    ]
